development:
  adapter: postgresql
  encoding: unicode
  database: standup_development
  pool: 5
  username: warstories
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: standup_test
  pool: 5
  username: warstories
    
# staging:
#   adapter: postgresql
#   encoding: unicode
#   database: puraoferta_staging
#   pool: 5
#   username: warstories
#   #password: sure_pass_db$

production:
  adapter: postgresql
  encoding: unicode
  database: standup_production
  pool: 5
#  username: prescriptionrex
#  password: pg#7~SS
